### ISSUE TITLE
您好,向您请教一个并发访问服务的问题,谢谢!

### ISSUE THREAD

**Issue by jevislee** [doocs/advanced-java#100]
比如下面的test服务里,我故意在里面让当前线程无限循环,这样第一次访问test服务就一直堵塞了,让我困惑的是第二次访问时为什么要等好几秒才能再访问到?tomcat里的线程池里不是有多个线程吗?一个线程堵塞没有返回,为什么不立即使用另外的线程继续服务,而是要等好几秒才会用另外的线程服务?
```
@RestController
public class TestController {

    @GetMapping(value = "/test")
    public String test() {
        System.out.println(Thread.currentThread().getId() + " send");
        while (true) {
            try {
                Thread.sleep(1);
            } catch (InterruptedException e) {
                System.out.println(e.getMessage());
            }
        }
    }
}
```

**Comment by alterhz** [comment]
看看线程池设置的初始线程数量，第二次访问可能是在新创建线程------------------ 原始邮件 ------------------
发件人: "jevislee"<notifications@github.com>
发送时间: 2019年8月30日(星期五) 下午4:24
收件人: "doocs/advanced-java"<advanced-java@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [doocs/advanced-java] 您好,向您请教一个并发访问服务的问题,谢谢! (#100)



比如下面的test&#x670D;务里,我故意在里面让当前线程无限循环,这样第一次访问test&#x670D;务就一直堵塞了,让我困惑的是第&#x4E8C;次访问时为什么要等好几秒才能再访问到?tomcat里的线程池里不是有多个线程吗?一个线程堵塞没有返回,为什么不立即使用另外的线程继续&#x670D;务,而是要等好几秒才会用另外的线程&#x670D;务?
 @RestController public class TestController {     @GetMapping(value = "/test")     public String test() {         System.out.println(Thread.currentThread().getId() + " send");         while (true) {             try {                 Thread.sleep(1);             } catch (InterruptedException e) {                 System.out.println(e.getMessage());             }         }     } }  
&mdash;

**Comment by jevislee** [comment]
application.yml里我只配置下面的参数作为测试
server:
  tomcat:
    max-threads: 5

理论上只要max-threads大于1,第一次访问让第一个线程堵塞了,第二次访问就应该立即使用第二个线程吧

**Comment by jevislee** [comment]
不好意思,可能是我用chrome测试的原因,我用postman测试就挺快的了
