### ISSUE TITLE
关于消息队列如何保证消息的顺序性的疑问？

### ISSUE THREAD

**Issue by xiongzhao1217** [doocs/advanced-java#101]
文中的解答不能覆盖这样的场景，在生产者有多个的情况下，业务实际发生顺序为，s1,s2,s3，比如变价消息，10元变9元再变11元，最终的商品价格应该是11元，但由于各个生产者发送mq的时间以及中间网络耗时不同，最终落到mq中的顺序可能变成，9元,11元,10元,即使消费者保证了顺序，结果也是不对的，我们的做法是在消息体中增加业务发生时间，每个消费者都会做后发先至逻辑判断，对于最近一次业务变动之前的消息进行忽略，希望作者能交流反馈。

**Comment by alterhz** [comment]
不错的方案，受教




------------------ 原始邮件 ------------------
发件人: "xiongzhao1217"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午2:32
收件人: "doocs/advanced-java"<advanced-java@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [doocs/advanced-java] 关于消息队列如何保证消息的顺序性的疑问？ (#101)




文中的解答不能覆盖这样的场景，在生产者有多个的情况下，业务实际发生顺序为，s1,s2,s3，比如变价消息，10元变9元再变11元，最终的商品价格应该是11元，但由于各个生产者发送mq的时间以及中间网络耗时不同，最终落到mq中的顺序可能变成，9元,11元,10元,即使消费者保证了顺序，结果也是不对的，我们的做法是在消息体中增加业务发生时间，每个消费者都会做后发先至逻辑判断，对于最近一次业务变动之前的消息进行忽略，希望作者能交流反馈。
 
&mdash;

**Comment by yanglbme** [comment]
@xiongzhao1217 方案可行，谢谢你的反馈。文章里提到的 case 确实没有 cover 所有的应用场景。
