### ISSUE TITLE
关于《如何保证缓存与数据库的双写一致性？》的讨论

### ISSUE THREAD

**Issue by xiongzhao1217** [doocs/advanced-java#102]
诚如作者所说，先删缓存再更新数据库在复杂场景下的处理过于复杂，相较于Cache Aside Pattern模式，也就是先更新数据库后删除缓存的方式，个人认为放在同一个事务下能很好的解决一致性问题，如果删除缓存失败，业务逻辑会抛出异常，数据库事务自然会回滚，就做到了要么双写都成功，要么双写都失败，如果失败可以重试，从经验来讲，写数据库失败比操作redis失败的概率要大很多。

**Comment by SJP-github** [comment]
兄弟，在亿级流量下你用事务搞双写一致不就卡爆了吗？双写一致性的问题，关键在于在恰当的时候让写和读进行串行化操作，这个切当的时候大概就是删除缓存的时候。关于删缓存失败，还可以给一条消息到消息队列，失败了再删一次。

**Comment by xiongzhao1217** [comment]
@SJP-github 数据库最大QPS只有4000，在亿级流量下肯定分库分表了，分库分表后用事务搞双写没问题啊
