### ISSUE TITLE
advanced-java/docs/high-concurrency/why-mq.md 中的图片显示不了

### ISSUE THREAD

**Issue by gdjkmax** [doocs/advanced-java#117]

**Comment by yanglbme** [comment]
@gdjkmax 你好，我这边显示没有问题，你也可以通过 https://doocs.gitee.io/advanced-java/#/docs/high-concurrency/why-mq 进行阅读学习（GitHub/Gitee 同步更新）。

**Comment by gdjkmax** [comment]
好的谢谢。
