### ISSUE TITLE
mq的顺序性保证部分，不是太理解

### ISSUE THREAD

**Issue by czzt1** [doocs/advanced-java#133]
按照文中的场景，三条操作顺序为增加、修改、删除，如果单queue单consumer导致了顺序错乱，那一定是consumer在执行三种操作的用时不同。如果是这样，那下文的解决方案我认为也没有解决这个问题啊。可能是我理解有误，还望包涵。

**Comment by yanglbme** [comment]
@czzt1 单 queue 单 consumer，可以在消费完一条之后手动 ack，然后接收另一条消息进行消费，并没有问题。

**Comment by czzt1** [comment]
已经理解，非常感谢回复。

发件人: Yang Libin <notifications@github.com>
答复: doocs/advanced-java <reply@reply.github.com>
日期: 2019年12月15日 星期日 09:59
收件人: doocs/advanced-java <advanced-java@noreply.github.com>
抄送: czzt1 <czzt1@outlook.com>, Mention <mention@noreply.github.com>
主题: Re: [doocs/advanced-java] mq的顺序性保证部分，不是太理解 (#133)


@czzt1<https://github.com/czzt1> 单 queue 单 consumer，可以在消费完一条之后手动 ack，然后接收另一条消息进行消费，并没有问题。
