### ISSUE TITLE
文档内点击链接404

### ISSUE THREAD

**Issue by flybobble** [doocs/advanced-java#135]
https://www.shiyanlou.com/library/advanced-java/docs/high-concurrency/why-mq
这页面下方系统可用性降低
系统引入的外部依赖越多，越容易挂掉。本来你就是 A 系统调用 BCD 三个系统的接口就好了，人 ABCD 四个系统好好的，没啥问题，你偏加个 MQ 进来，万一 MQ 挂了咋整，MQ 一挂，整套系统崩溃的，你不就完了？如何保证消息队列的高可用，**可以点击这里查看**。

系统复杂度提高
硬生生加个 MQ 进来，你怎么**保证消息没有重复消费**？怎么**处理消息丢失的情况**？怎么保证消息传递的顺序性？头大头大，问题一大堆，痛苦不已。

加粗位置点击404

**Comment by yanglbme** [comment]
@flybobble 你好，谢谢反馈。

实验楼的文档是直接通过 GitHub 同步过去的，因为 GitHub 文档内容都是通过相对引用的方式链接的，同步的时候，可能有些问题。

你不妨通过 https://doocs.github.io/advanced-java/#/ 或者 https://doocs.gitee.io/advanced-java/#/ 进行阅读学习。
