### ISSUE TITLE
缓存与数据库双写一致性的问题

### ISSUE THREAD

**Issue by Eclipse-xp** [doocs/advanced-java#137]
您好，
请问在处理缓存与数据库双写一致性的问题时，为什么不是这样:
  先更新数据库再删除缓存，然后整个操作放到一个事务中，如果删除缓存成功再提交数据库事务，失败则回滚。
这样既保证了一致性，又简化了过程

**Comment by Eclipse-xp** [comment]
@yanglbme  能帮忙解答下么 感谢

**Comment by yanglbme** [comment]
@Eclipse-xp 考虑到效率问题，简单粗暴地使用事务保证一致性，可能不是一个好的方案。
