### ISSUE TITLE
[消息队列] mq 中的消息过期失效了

### ISSUE THREAD

**Issue by LyndonZhao** [doocs/advanced-java#138]
假设你用的是 RabbitMQ，RabbtiMQ 是可以设置过期时间的，也就是 TTL。如果消息在 queue 中积压超过一定的时间就会被 RabbitMQ 给清理掉，这个数据就没了。那这就是第二个坑了。这就不是说数据会大量积压在 mq 里，而是大量的数据会直接搞丢.
--------------------------------------
首先十分感谢Yang大咖整理这么多好的面试资料。
其次，请问Yang大咖， 关于这个问题，能否用死信队列来解决呢？
感谢百忙之中回复^^

**Comment by SuperBaBa** [comment]
先说下场景哈，个人使用的是RocketMQ在翻看了源码后大致了解到MQ消息持久化是存储在commitlog文件中的（默认1G），而consumerQueue只保存在了该队列在commitlog中的映射信息，死信队列和重试队列也是同理，如果消息丢失不是映射文件丢失，就应该是commitlog丢失了，所以个人感觉死信队列应该找不回来
