### ISSUE TITLE
关于es的写数据底层原理

### ISSUE THREAD

**Issue by primejava** [doocs/advanced-java#150]
听了几次还是很迷惑，不明白segment file里面的数据到底在什么时候写进去的
是
1.segment file是大约1s创建一个，并且同时将内存buffer里面的数据写入到segment file里面？
或者是
2.segment file是大约1s创建一个，但并不往里面写数据，而是等大约30分钟以后在执行commit操作的时候把os cache里面的数据全部刷新到一个个的segment file里面?

**Comment by misstt123** [comment]
我也有同样的迷惑

**Comment by vicya** [comment]
@primejava 就是你说的第一个呀，segment file 首先写内存，然后定时通过os cache刷进磁盘。
