### ISSUE TITLE
Wanted | 招聘帖（社招、校招、实习）

### ISSUE THREAD

**Issue by yanglbme** [doocs/advanced-java#156]
> 候选人投递简历前，请务必确认招聘人信息，防止个人信息泄露给陌生人。招聘人请统一按以下格式创建招聘信息，谢谢。

## 公司/团队介绍
...

## 联系方式
- 邮箱
- 微信/手机号
- 其它

注：最好提供企业邮箱，证明身份。

**Comment by yanglbme** [comment]
## 公司/团队介绍
我们是 AliExpress 用户增长团队，不知道 AliExpress？你可以认为是对面歪果仁的淘宝，用户增长大有可为，想了解更多的话，直接联系我吧，我给你一对一的介绍。

注：本信息由 @ding102992 提供，见 #155。

## 联系方式
- 邮箱：mingmeng.dmm@alibaba-inc.com
- 微信：ding102992

**Comment by chenqimiao** [comment]
## 公司/团队介绍
天猫国际是中国消费升级的第一跨境平台，是阿里经济体5年2000亿美金进口承诺的主力军。2019年天猫国际技术部和考拉合并成立了阿里巴巴大进口技术部，是阿里巴巴国际化战略的核心技术部门。致力于进口业务的技术突破和创新，助力中国的消费者实现“买遍全球”的需求，跨入未来的万亿级市场。想了解更多的话，直接联系我吧，我帮你组内直推，大量HC，走过路过不可错过。
注：本信息由 @hunterzhang86 提供，见 #157。

## 联系方式
- 邮箱：yifeng.zh@alibaba-inc.com
- 微信：isHunterZhang

**Comment by Nerom** [comment]
阿里直招，社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会

**Comment by ZhenghaeHo** [comment]
> ## 公司/团队介绍
> 我们是 AliExpress 用户增长团队，不知道 AliExpress？你可以认为是对面歪果仁的淘宝，用户增长大有可为，想了解更多的话，直接联系我吧，我给你一对一的介绍。
> 
> 注：本信息由 @ding102992 提供，见 #155。
> 
> ## 联系方式
> * 邮箱：[mingmeng.dmm@alibaba-inc.com](mailto:mingmeng.dmm@alibaba-inc.com)
> * 微信：ding102992

base在哪个城市

**Comment by ZhenghaeHo** [comment]
> 阿里直招，社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
> 校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会
> 
> # 公司/团队介绍
> 我们是阿里巴巴集团新零售技术旗下供应链技术国际化团队，我们致力于通过世界一流的全球化技术服务来自全球10亿+的海外消费者，为全球消费者带去极致的购物体验，让买全球卖全球的使命落地成为普惠全球的显示图景。我们服务的业务实体有 lazada、AliExpress、天猫海外、Daraz、Trendyol等平台。
> 
> # 联系方式
> 邮箱： [liuzhu.wlz@alibaba-inc.com](mailto:liuzhu.wlz@alibaba-inc.com)

@Nerom base在哪个城市

**Comment by ZhenghaeHo** [comment]
@

> ## 公司/团队介绍
> 天猫国际是中国消费升级的第一跨境平台，是阿里经济体5年2000亿美金进口承诺的主力军。2019年天猫国际技术部和考拉合并成立了阿里巴巴大进口技术部，是阿里巴巴国际化战略的核心技术部门。致力于进口业务的技术突破和创新，助力中国的消费者实现“买遍全球”的需求，跨入未来的万亿级市场。想了解更多的话，直接联系我吧，我帮你组内直推，大量HC，走过路过不可错过。
> 注：本信息由 @hunterzhang86 提供，见 #157。
> 
> ## 联系方式
> * 邮箱：[yifeng.zh@alibaba-inc.com](mailto:yifeng.zh@alibaba-inc.com)
> * 微信：isHunterZhang

@chenqimiao base在哪

**Comment by hepin1989** [comment]
# 公司/团队介绍
阿里巴巴消息业务/基础团队招聘（校招/社招）直招，社招校招均有。
商业链接，通过消息，场景触达、链接商家和消费者。为商家的经营决策做贡献。
在提供手淘、天猫的消息、营销推送的能力同时；同时，我们也提供了开放的二方支持能力，支持直播、钉钉直播、钉钉海外直播、手淘、天猫、闲鱼、飞猪、零售通、躺平等二方App的消息能力。
招聘岗位：Java 后端、Android客户端、iOS客户端、CPP跨终端
联系方式
邮箱： hepin.p@alibaba-inc.com
base: 杭州、阿里巴巴西溪园区
