### ISSUE TITLE
1元秒杀！Flink 从入门到进阶，大厂必备的大数据前沿技术，42 讲带你轻松通关！(1元优惠仅限4月16日晚24点以前)，点此获取☞

### ISSUE THREAD

**Issue by gnehsuy** [doocs/advanced-java#159]
![10ce3ae3d1c98a93cb98236ceca5548](https://user-images.githubusercontent.com/13401581/79427254-eb9f7600-7ff6-11ea-9b7b-4e360914b130.png)

**Comment by yanglbme** [comment]
已封禁用户 @gnehsuy 

> gnehsuy has been blocked from the doocs organization and will receive an email notification.
