### ISSUE TITLE
Dubbo负载均衡一致性Hash策略单词拼写错误？

### ISSUE THREAD

**Issue by YANGJINJUE** [doocs/advanced-java#165]
应该是ConsistentHash

**Comment by yanglbme** [comment]
@YANGJINJUE 谢谢反馈，已更正。

**Comment by YANGJINJUE** [comment]
https://doocs.gitee.io/advanced-java/#/./docs/distributed-system/dubbo-load-balancing

**Comment by yanglbme** [comment]
已经同步更新。

![image](https://user-images.githubusercontent.com/21008209/81467554-e60b0980-920b-11ea-8c66-12836f209915.png)
