### ISSUE TITLE
感谢作者大大，收获良多

### ISSUE THREAD

**Issue by endlonelycat** [doocs/advanced-java#169]
在这里感谢下作者，说实话我第一眼看到这个文档的时候是感觉很惊讶很详细，很多都是我没想过甚至想不到的问题，在这里都看到，解决了很多之前不知道的问题，谢谢作者大大了。大大还是不要受到不良言语的影响，还是有很多人支持你的！！！！

**Comment by yanglbme** [comment]
@endlonelycat 谢谢，我相信这个项目或多或少能帮助到一些朋友，这些也就足够了，其他的我不会在意了。非常感谢你们的支持。
