### ISSUE TITLE
这不就是copy中华石杉老师的讲课吗？

### ISSUE THREAD

**Issue by keepongjl** [doocs/advanced-java#17]
不知道你是不是中华石杉老师，如果不是的还，还请标明知识点的出路

**Comment by yanglbme** [comment]
@keepongjl 你好，谢谢反馈。

- 我在文档一开始就在 README 中写明了出处，我是做了一个系统的整理，方便学习查阅，不知道这样为什么还会让你有疑惑。
- 关于这件事，我在私下通过公众号跟中华石杉沟通过，他是知晓的哈。
- 我定位为“知识扫盲”，也是希望这个知识仓库，不只是对有某些特殊需求的人有所帮助，还希望可以作为一些初中级开发者的一份学习材料。
- 同时我也希望大家如果觉得好的话，可以关注**中华石杉的公众号**（石杉的架构笔记），学习更多的架构知识。
- 网上太多直接贴了他人文章，却自己申明原创的，完全是不尊重别人劳动成果的体现。

**Comment by yanglbme** [comment]
@keepongjl 有其它的疑惑，欢迎随时反馈。

**Comment by keepongjl** [comment]
没细看，不好意思哈
