### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by liuhonbin** [doocs/advanced-java#178]
本项目大部分内容来自中华石杉，版权归作者所有，内容涵盖高并发、分布式、高可用、微服务、海量数据处理等领域知识。我对这部分知识做了一个系统的整理，方便学习查阅。这个是作者的原话，但是看起来你的和那个石衫的仓库的内容一模一样啊，那我clone一下你的仓库，是不是也可以说，内容归你，版权归我啊？？？？

**Comment by RocketTH** [comment]
这个仓库的内容可以说百分之九十九都是出自中华石衫原创，如果按照他这么说，我能不能clone spring的仓库文档，然后发布到自己的repo，本项目大部分内容来自spring，版权归我所有。

**Comment by yanglbme** [comment]
#45
