### ISSUE TITLE
作者能不能证明回答一下版权问题啊

### ISSUE THREAD

**Issue by liuhonbin** [doocs/advanced-java#179]
你是不是拿来主义来的太舒服了，你敢在公众公开发文说别人抄袭你吗，你说你有劳动，你说的是ctrl c + ctrl v，你也不要和我说什么其他的东西，你只需要说下这个版权的问题，毕竟做人不能这么无耻

**Comment by javaroom** [comment]
如果是照搬照抄，我觉得要加上声明。如果有自己的理解观点可以不用。gosling发明了java，是不是所有的java书都要写gosling的版权？消化了成自己的，再用自己的方式写出来，就是你的。
如果这么整，一个好的项目又死了，何必呢？


| |
javaroom
|
|
邮箱：javaroom@163.com
|

Signature is customized by Netease Mail Master

在2020年07月27日 11:56，liuhonbin 写道：

你是不是拿来主义来的太舒服了，你敢在公众公开发文说别人抄袭你吗，你说你有劳动，你说的是ctrl c + ctrl v，你也不要和我说什么其他的东西，你只需要说下这个版权的问题，毕竟做人不能这么无耻

**Comment by liuhonbin** [comment]
> 如果是照搬照抄，我觉得要加上声明。如果有自己的理解观点可以不用。gosling发明了java，是不是所有的java书都要写gosling的版权？消化了成自己的，再用自己的方式写出来，就是你的。 如果这么整，一个好的项目又死了，何必呢？ | | javaroom | | 邮箱：javaroom@163.com | Signature is customized by Netease Mail Master 在2020年07月27日 11:56，liuhonbin 写道： 你是不是拿来主义来的太舒服了，你敢在公众公开发文说别人抄袭你吗，你说你有劳动，你说的是ctrl c + ctrl v，你也不要和我说什么其他的东西，你只需要说下这个版权的问题，毕竟做人不能这么无耻 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

作者自己说：本项目大部分内容来自中华石杉，版权归作者所有，我是觉得这句话很迷，大部分是多少，百分之99？还是多少，
如果一个项目百分之99都是别人地方抄过来的，我觉得作者要正式一下自己，最起码你的项目简介的写请求

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/88504034-fe6a1380-d005-11ea-8a0e-89951618e3bf.png)
