### ISSUE TITLE
缓存与数据库的双写一致性的问题

### ISSUE THREAD

**Issue by plutozc** [doocs/advanced-java#18]
我想问下 对于队列处理数据库更新的操作 缓存是如何返回呢 如果是读不到睡眠的话 是不是会存在睡眠中缓存更新了又有更新请求进来 又把缓存删了的问题 导致一直读不到缓存？

**Comment by yanglbme** [comment]
@plutozc 你好，你说的这种情况，有可能出现，就是内存队列中积压了很多的更新操作。但其实一般来说，数据的写频率是比较低的。但如果真的出现这种情况，可以考虑加机器，让每个机器上部署的服务实例处理更少的数据。同时也要根据一些具体的业务场景，做好各种压力测试。

稍后我会在文章中做一些补充说明。
