### ISSUE TITLE
LeastActiveLoadBalance

### ISSUE THREAD

**Issue by ganxinming** [doocs/advanced-java#190]
在dubbo负载均衡中那章中，LeastActiveLoadBalance
这个就是自动感知一下，如果某个机器性能越差，那么接收的请求越少，越不活跃，此时就会给不活跃的性能差的机器更少的请求。
官网给的回答是如下:
LeastActiveLoadBalance 翻译过来是最小活跃数负载均衡。活跃调用数越小，表明该服务提供者效率越高，单位时间内可处理更多的请求。此时应优先将请求分配给该服务提供者
活跃数越少，越能说明机器处理能力强或越空闲

**Comment by yanglbme** [comment]
此前的文档描述不是很恰当，目前已修改，谢谢反馈。@ganxinming
