### ISSUE TITLE
未来之路 | The future path

### ISSUE THREAD

**Issue by yanglbme** [doocs/advanced-java#20]
# 未来之路
> 来自 @mercyblitz (小马哥)

## 懂得取舍
- [ ] 挑选书籍
- [ ] 学习源码
- [ ] 职业规划

## 学会判断
- [ ] 使用场景判断
- [ ] 发展趋势判断
- [ ] 可行性判断

## 学习方法
- [ ] 多看（代码、规范、论文）
- [ ] 多写（模仿、比较、超越）
- [ ] 多思考（正向、逆向、跳跃）
- [ ] 少废话（吹牛、装逼、叫大哥）

**Comment by MrEric125** [comment]
有哪些进阶推荐的书籍

**Comment by yanglbme** [comment]
可以看看 [technical-books](https://github.com/doocs/technical-books) 的书籍推荐，当然，进阶的前提是基础要打牢。

**Comment by MrEric125** [comment]
好的，谢谢，多学习，多提升

**Comment by bee06** [comment]
多培养下产品化的思维

**Comment by SuperBaBa** [comment]
职业规划到底是怎样的呢，个人有些见解，往大佬们斧正
1、根据日后的岗位决定自己的技术栈，学习技术
2、为自己的努力设定目标，如：今年某某厂明年某某大厂
3、增加自身技能认证，如软考、POM等
