### ISSUE TITLE
招聘帖

### ISSUE THREAD

**Issue by shuxiaotai** [doocs/advanced-java#202]
### **公司/团队介绍**
我们是涂鸦智能工程生产力团队，无论你是java、python、测试、安卓、前端还是go，我们都招，具体岗位详情如下
坐标：杭州西湖区华策中心A座 

**一. 高级Java开发工程师**

岗位职责：
1、负责IoT测试基础设施建设，主要包括云端链路测试及稳定性监控平台、性能测试
平台、嵌⼊式固件平台；
2、优化各平台定时任务调度、任务执⾏器、⽇志采集系统，保证⾼并发稳定性、可
⽤性、实时性；
3、深⼊理解公司云端、嵌⼊式、测试相关业务流程，分析问题，制定解决⽅案，进
⾏架构设计并⾼效实施满地；
4、对技术有热情，持续学习，乐于熟悉新的技术产品。 
岗位要求：
1、熟悉Java语言，对相关技术领域的开源产品有深入的理解；
2、熟悉分布式、性能调优、缓存、消息、搜索等机制；
3、熟悉MySQL等数据库中的一种或多种，有数据库调优经验，了解MySQL及相关分布式存储技术；
4、思维清晰，头脑灵活，能独立分析并解决复杂的线上问题；
5、三年以上Java相关的开发经验。
加分项：
1）熟悉Golang者优先；
2）熟悉python/ruby等脚本语言者优先；
3）有K8S相关经验者优先；

**二. Android开发工程师**

岗位描述

1）独立完成 Android客户端程序的开发，相关功能预研和研究；

2）根据产品需求设计并开发相关的移动产品；

3）验证和修正测试中发现的问题；

4）一些终端命令工具开发;

岗位要求：

1）计算机或相关专业本科以上学历；

2）对数据结构和算法设计具有深刻的理解；

3）熟悉掌握Java，熟悉Android SDK；

4）一年以上Android开发经验，能独立开发Android App；

5）善于学习和运用新知识，具有良好的分析和解决问题能力；

6）具有良好的团队合作精神和积极主动的沟通意识；

加分项：

1）熟悉Appium；

2）有Flutter开发经验；

3）熟练运用算法和数据结构；

4）熟悉Python/Ruby等脚本语言；

5）有Golang经验，终端工具开发经验者优先

6）有性能优化项目经验。

**三. Golang开发工程师**

职位描述：

1、负责设计, 完善内部CI系统, 包管理工具研发等，结合需求设计实现安全、稳定、高伸缩性、高性能、易维护、易用性好的业务系统

2、根据系统发展，对技术架构不断调整，持续优化。

3、与运维同学合作，实现平台服务的可用性管理，如变更、故障、监控、容量等方向的自动化与平台化工作

职位要求：

1 、熟悉算法、数据结构和常用的设计模式；

2、2-5年开发工作经验, 具有良好的英文阅读能力, 熟悉Golang生产环境开发工作经验, 熟悉 Golang 并发编程

3、熟悉分布式数据库的设计原理，熟悉NoSQL，有 RocksDB、Redis、MongoDB等常见NoSQL数据库的实际使用和开发经验

4、熟悉Docker基本原理及工具使用, 熟悉K8S 者加分

5、熟悉Socket 网络编程者优先

6、具有良好的技术钻研能力，能够深入底层解决技术难题

7、有强烈的责任心和团队精神，善于沟通和合作

**四. 测试开发工程师**

岗位职责：

1、参与云服务接口、物联网设备接口测试；

2、参与或构建与业务匹配的自动化框架及自动化解决方案，引领团队建立物联网的自动化测试体系；

3、参与或构建云服务的持续集成，与开发、运维一起构建公司的CI、CD流程和系统；

4、基于在线工具平台建立各种小工具，提高测试效率；

5、可参与到业务中提供测试架构、流程、工具等方面的技术支持。

岗位要求：

1、具备较强的分析、解决问题的能力，熟练掌握至少一种常用编程语言，如Java、Python、C++、C#等；

2、对常用协议如HTTP、Dubbo等有一定了解，熟练掌握多种测试工具，如JMeter、Charles、Jira、禅道等；

3、对测试感兴趣，很强的责任心，良好的沟通能力和表达能力，能承受一定的工作压力；

4、有过1年以上大型服务测试经验者，或3年以上测试开发经验者优先；

5、有使用过常用测试框架JUnit、TestNG、PYUnit、JMeter性能扩展等并对框架有定制能力者优先；

6、有物联网自动化测试经验、Golang、或对QTPP协议有了解或涂鸦生态开发者优先。

**五. Python开发工程师**

职位描述： 

1、负责功能设计、开发、维护 

2、根据系统发展，对技术架构不断调整，持续优化

职位要求：

 1 、至少一年以上python web端后台开发经验

 2、熟练掌握Django、[Web.py](http://web.py/)、Tornado、Flask等至少1个Web开发框架 

3、有丰富web后端系统性能调优经验优先 

4、熟悉Linux环境下的开发 

5、熟悉mysql数据库，有数据库调优经验的优先 

6、具有良好的技术钻研能力，能够深入底层解决技术难题 7、有强烈的责任心和团队精神，善于沟通和合作

**六. 前端开发工程师** 

岗位描述：

我们负责涂鸦IoT平台开发，目标是通过前端技术，让物联网行业的数据、应用可以高效、自由的开发和流转。；

我们关注： 

1. Web应用、组件库、数据可视化、工程工具、BFF等；

2. 网站、平台、无线等业务的前端开发； 

3. 设计并实现物联网场景下，面向开发者的应用开发框架；

工作内容：

1. 参与PC、APP Hybrid、小程序、数据可视化等前端开发；

2. 参与改进开发、构建、发布等前端工程化体系；

3. 参与公司内部系统建设（包括Node全栈开发）；

任职要求：

1. 本科及以上学历，有至少1年以上前端工作经验；

2. 熟练使用HTML、CSS、JavaScript等前端技术，熟悉HTTP协议以及浏览器原理；

3. 至少熟练运用一种前端开发框架并掌握其原理如: Vue.js/React.js及其生态圈；

4. 具备良好的沟通能力和优秀的团队协作精神；

符合以下任一条件者优先：

熟悉一门非前端的语言 如:Java/PHP/Python/Ruby等，并有实践经验;

参与开源项目并贡献过代码，附上Github链接；

熟练使用 git、github、linux 等工具。

### **联系方式**
shuxiaotai@gmail.com

**Comment by chenqimiao** [comment]
#156

**Comment by yanglbme** [comment]
已转移
