### ISSUE TITLE
redis的分布式锁redlock描述感觉有点问题

### ISSUE THREAD

**Issue by fiany** [doocs/advanced-java#210]
[https://github.com/doocs/advanced-java/blob/main/docs/distributed-system/distributed-lock-redis-vs-zookeeper.md](url)

> 1.获取当前时间戳，单位是毫秒；
> 2.跟上面类似，轮流尝试在每个 master 节点上创建锁，过期时间较短，一般就几十毫秒；
> 3.尝试在大多数节点上建立一个锁，比如 5 个节点就要求是 3 个节点 n / 2 + 1 ；
> 4.客户端计算建立好锁的时间，如果建立锁的时间小于超时时间，就算建立成功了；
> 5.要是锁建立失败了，那么就依次之前建立过的锁删除；
> 6.只要别人建立了一把分布式锁，你就得不断轮询去尝试获取锁。

上面第二步这里应该是有两个时间一个是锁的过期时间比如10s（用于在redis中设置key的过期时间）。一个是锁的超时时间用于程序中下面计算超时时间比如50ms。这里会给人一种误导，以为超时时间就是redis中key的过期时间。

**Comment by yanglbme** [comment]
@fiany 是的，这里描述有问题，我现在改一下。谢谢反馈哈
