### ISSUE TITLE
能不能添加redis主从复制，如何保证一致性的问题和答案。

### ISSUE THREAD

**Issue by wardseptember** [doocs/advanced-java#214]
能不能添加redis主从复制，如何保证一致性的问题和答案。
如何保证redis主存和从数据库的数据一致性。

**Comment by niwzb** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： aaronnejad110 ***@***.***>日期： 2021年7月25日周日 清晨5:40收件人： doocs/advanced-java ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [doocs/advanced-java] 能不能添加redis主从复制，如何保证一致性的问题和答案。 (#214)
Hi i have forgot my password I can not login to my account via phone backup code app but I have previous passwords and backup codes. What can I do? Email me at ***@***.*** if you can help thanks.
