### ISSUE TITLE
No Table of Contents in PDF

### ISSUE THREAD

**Issue by nlpsuge** [doocs/advanced-java#244]
Hi,
I tried to run docsify-pdf-converter within IDEA like:
![image](https://user-images.githubusercontent.com/2271720/136645397-4a82cbdb-a880-45a9-ad19-728287c9ca84.png)
It can generate a file named `advanced-java.pdf`, but **without the Table of Contents**.

The same issue as project [jvm](https://github.com/doocs/jvm)

Any advice?

**Comment by yanglbme** [comment]
Yes, you can add the table of contents manually :)

**Comment by nlpsuge** [comment]
> Yes, you can add the table of contents manually :)

How? Can you give me some links or an example?
