### ISSUE TITLE
你收到了一份加入请求

### ISSUE THREAD

**Issue by Yangyy99** [doocs/advanced-java#248]
无意中看到了这个项目 ，感觉这才是互联网开源精神 帮助大家提升能力 ，我也想加入组织

**Comment by yongroot** [comment]
邮件已经正常接收。我会尽早查看，谢谢。

**Comment by zhFuture** [comment]
您好，我将尽快给您回复。

**Comment by TopMonster** [comment]
邮件已经收到 谢谢~！

**Comment by onions1111** [comment]
信件已收到。

**Comment by yanglbme** [comment]
> 无意中看到了这个项目 ，感觉这才是互联网开源精神 帮助大家提升能力 ，我也想加入组织  

好的，晚点给你发邀请

**Comment by yanglbme** [comment]
@Yangyy99 你好，已发送邀请，请及时访问 https://github.com/doocs 接受邀请，欢迎加入我们~

这个 issue 我先关了

**Comment by Yangyy99** [comment]
@yanglbme  好的 已经加入 ，朋友
