### ISSUE TITLE
阿里巴巴国际中台云原生技术团队持续招聘P5/P6/P7

### ISSUE THREAD

**Issue by bieberHe** [doocs/advanced-java#251]
阿里国际化中台平台架构还有大量HC，p5、p6、p7都要，我们以云原生为技术底座，以国际化为场景，定义新的技术架构、业务架构，建设可持续演进的技术产品平台…欢迎加入我们一起定义业务视角下的最佳实践…你有机会参与面相全球多地域的容灾架构设计、复杂国际电商业务中台架构设计、云原生基础架构设计（Mesh化、镜像编排、serverless、faas）、国际化多地域租户架构设计。团队nice，拒绝内卷，拒绝PUA！！投递简历：bibo.hbb#alibaba-inc.com

**Comment by zhrgithub** [comment]
ok


| |
张泓锐
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年02月18日 ***@***.***> 写道：

阿里国际化中台平台架构还有大量HC，p5、p6、p7都要，我们以云原生为技术底座，以国际化为场景，定义新的技术架构、业务架构，建设可持续演进的技术产品平台…欢迎加入我们一起定义业务视角下的最佳实践…你有机会参与面相全球多地域的容灾架构设计、复杂国际电商业务中台架构设计、云原生基础架构设计（Mesh化、镜像编排、serverless、faas）、国际化多地域租户架构设计。团队nice，拒绝内卷，拒绝PUA！！投递简历：bibo.hbb#alibaba-inc.com

**Comment by zhrgithub** [comment]
bibo.hbb#alibaba-inc.com这个是邮箱吗
