### ISSUE TITLE
关于题目：如何在大量的数据中判断一个数是否存在

### ISSUE THREAD

**Issue by hiwja** [doocs/advanced-java#254]
想不通为啥要用分治法呢？IO流一遍就能找出来是否存在

**Comment by zhrgithub** [comment]
你知道为什么要性能调优吗？


| |
zhr
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年03月6日 ***@***.***> 写道：

想不通为啥要用分治法呢？IO流一遍就能找出来是否存在

**Comment by zhrgithub** [comment]
存在 但是效率低



| |
zhr
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月06日 21:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [doocs/advanced-java] 关于题目：如何在大量的数据中判断一个数是否存在 (Issue #254) |

想不通为啥要用分治法呢？IO流一遍就能找出来是否存在
