### ISSUE TITLE
发现一处错误拼写

### ISSUE THREAD

**Issue by Protosskrz** [doocs/advanced-java#261]
发现一处错误拼写
【ES 的核心概念】-》Index介绍栏
索引包含了一堆有相似结构的文档数据，比如商品索引。一个索引包含很多 document，一个索引就代表了一类相似或者相同的 **ducument**。

ducument应当为document？

**Comment by yanglbme** [comment]
是的，写错了，欢迎提交 pull request 参与修改 @Protosskrz

**Comment by CodeWarriors0** [comment]
乐意加入项目，下次发现问题会直接 pull request 。请问可以拉我进一下开源社区吗，JVM方面我也发现了一些问题，邮箱申请后一直没有收到回复！

**Comment by yanglbme** [comment]
@CodeWarriors0 已发邀请，欢迎加入
