### ISSUE TITLE
Is there an error about Delay-double-deletion's example code?

### ISSUE THREAD

**Issue by alanchenggang** [doocs/advanced-java#282]
There is an error in the code about delayed-double-deletion in the article<如何保证缓存与数据库的双写一致性>
```java
public void set(key, value) {
    putToDb(key, value);
    deleteFromRedis(key);
    // ... a few seconds later
    deleteFromRedis(key);
}
```
And i google about this concept got this picture
![image](https://user-images.githubusercontent.com/50035191/210315282-a584eb71-31bc-467b-bf4a-b72c6ebac07b.png)

**Comment by lujocom** [comment]
您的邮件我已收到！我会尽快回复您的！！！

**Comment by xiaopan1916** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，~您的邮件我已收到，谢谢！

**Comment by yongroot** [comment]
邮件已经正常接收。我会尽早查看，谢谢。

**Comment by TopMonster** [comment]
邮件已经收到 谢谢~！

**Comment by zhFuture** [comment]
您好，我将尽快给您回复。

**Comment by nielongguang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kevin0016** [comment]
自动回复：您好，我是梁学凯，信已收到，

**Comment by huxiqiang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by onions1111** [comment]
信件已收到。

**Comment by zgczjc** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近很忙，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yanglbme** [comment]
一堆自动回复啊

**Comment by alanchenggang** [comment]
> 一堆自动回复啊

这个延时双删是有问题不？

**Comment by yanglbme** [comment]
都是先延迟一段时间，再次删除缓存。没啥问题哈

**Comment by alanchenggang** [comment]
> 都是先延迟一段时间，再次删除缓存。没啥问题哈
我谷歌的都是这样的 类似环绕通知
```java
public void set(key, value) {
 
    deleteFromRedis(key);
   putToDb(key, value);
    // ... a few seconds later
    deleteFromRedis(key);
}
```
