### ISSUE TITLE
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3.   ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter  项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### ISSUE THREAD

**Issue by swordbe** [doocs/advanced-java#283]
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia.
Flutter is making efforts to games, Metaverse, and web3.  
![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png)
https://github.com/flutter/flutter

项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。
Flutter正在向游戏、元宇宙、web3发力。

**Comment by xiaopan1916** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，~您的邮件我已收到，谢谢！

**Comment by lujocom** [comment]
您的邮件我已收到！我会尽快回复您的！！！

**Comment by zhFuture** [comment]
您好，我将尽快给您回复。

**Comment by TopMonster** [comment]
邮件已经收到 谢谢~！

**Comment by nielongguang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huxiqiang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kevin0016** [comment]
自动回复：您好，我是梁学凯，信已收到，

**Comment by onions1111** [comment]
信件已收到。
