### ISSUE TITLE
ES深度分页问题

### ISSUE THREAD

**Issue by CavaliersFor** [doocs/advanced-java#32]
[该文章](https://github.com/doocs/advanced-java/blob/master/docs/high-concurrency/es-optimizing-query-performance.md)提到的深度分页问题还有一种解决方法：
使用 Search After。
局限是：不能指定页数，只能下一页的查询。需要指定sort值，并且唯一

**Comment by yanglbme** [comment]
@CavaliersFor 感谢反馈，稍后我做一下补充说明 :)
