### ISSUE TITLE
分布式服务接口请求的顺序性如何保证？

### ISSUE THREAD

**Issue by chenlang888881** [doocs/advanced-java#34]
分布式服务接口请求的顺序性如何保证？你举例中说服务 A 调用服务 B，先插入再删除。我觉得调用服务B的时候就要保证它的顺序性，不然会出错，就是同步调用。不会出现两请求都过去。还是我理解不到位，请解释下。

**Comment by yanglbme** [comment]
@chenlang888881 一个服务可以部署在多台机器上，多个请求可能落到该服务的不同机器上，是这个意思。

**Comment by chenlang888881** [comment]
> @chenlang888881 一个服务可以部署在多台机器上，多个请求可能落到该服务的不同机器上，是这个意思。

但是感觉这种情况我会在消费端控制，需要先插入完成，我才会掉用删除。这种情况一般不会用异步吧。
