### ISSUE TITLE
es 的分布式架构原理能说一下么小建议

### ISSUE THREAD

**Issue by ziningmei** [doocs/advanced-java#35]
这篇文章，在es5.x的版本，index可以类比为mysql的数据库，type类比为mysql的表

**Comment by yanglbme** [comment]
@ziningmei 你好，你的意思是说加上 **在 es5.x 版本中** 这个描述？

**Comment by ziningmei** [comment]
我的意思是index 类比为 db ，type 类比为表，这样比较好理解

**Comment by ziningmei** [comment]
那是不是这篇文章[es 的分布式架构原理](https://github.com/doocs/advanced-java/blob/master/docs/high-concurrency/es-architecture.md)里面内容也同步一下

**Comment by yanglbme** [comment]
@ziningmei 这个应该就不再写一次啦，其实我在 [es 分布式架构原理](https://github.com/doocs/advanced-java/blob/master/docs/high-concurrency/es-architecture.md) 这篇文章里，也有稍微提到。我相信读者按顺序阅读下来，应该能理解的 :) 
![image](https://user-images.githubusercontent.com/21008209/52055554-af6f2980-259a-11e9-92e1-be674b8e7404.png)

当然，如果你有更好的想法，也欢迎提交 PR。
