### ISSUE TITLE
消息队列，为什么使用消息队列？文章中的一个mq使用建议：

### ISSUE THREAD

**Issue by rainzhao** [doocs/advanced-java#40]
原文： 不过现在确实越来越多的公司，会去用 RocketMQ，确实很不错（阿里出品），但社区可能有突然黄掉的风险，对自己公司技术实力有绝对自信的，推荐用 RocketMQ，否则回去老老实实用 RabbitMQ 吧，人家有活跃的开源社区，绝对不会黄。

文中关于RocketMQ突然黄掉的风险，应该不会了，目前阿里RocketMq 已捐赠至Apache基金会。

**Comment by yanglbme** [comment]
@rainzhao 好的，谢谢反馈，我稍后在文章里简单做一下修改。
