### ISSUE TITLE
章节小建议

### ISSUE THREAD

**Issue by zhongmc1995** [doocs/advanced-java#42]
## 如何保证缓存与数据库的双写一致性？
https://github.com/doocs/advanced-java/blob/master/docs/high-concurrency/redis-consistence.md

这一章中 `比较复杂的数据不一致问题分析 ` 中的描述没太看懂，是否可以使用一个列子细化讲解下

**Comment by yanglbme** [comment]
@zhongmc1995 你好，谢谢反馈。用一个例子细化来讲解的话，可能篇幅会很长。

**Comment by yanglbme** [comment]
@zhongmc1995 之后可能会增加，目前暂时关了哈~
