### ISSUE TITLE
可以增加一个落地项目介绍思考环节，可以把遇到的相关组件的使用心得做分享 | Add a module to share experiences in using the technology component

### ISSUE THREAD

**Issue by jerryldh** [doocs/advanced-java#46]
可以增加一个落地项目介绍思考环节，可以把遇到的相关组件的使用心得做分享

**Comment by yanglbme** [comment]
:) 谢谢你的建议 @jerryldh

如果可以的话，我更倾向于开一个模块，让读者都能贡献自己项目中的一些思考与心得。但目前暂且不开哈。

**Comment by jerryldh** [comment]
> :) 谢谢你的建议 @jerryldh
> 
> 如果可以的话，我更倾向于开一个模块，让读者都能贡献自己项目中的一些思考与心得。但目前暂且不开哈。

说的就是这个意思

**Comment by BigBlackSheep** [comment]
期待...

**Comment by sunyuanpinggithub** [comment]
> > :) 谢谢你的建议 @jerryldh
> > 如果可以的话，我更倾向于开一个模块，让读者都能贡献自己项目中的一些思考与心得。但目前暂且不开哈。
> 
> 说的就是这个意思
同意

**Comment by yanglbme** [comment]
谢谢大家的反馈。

因为原先只有一位朋友反馈了这个需求，所以我在考虑是否有必要添加。而现在收到多位朋友的反馈，那么，今天此项目会更新一个模块 `from-readers`，期待 GitHub 朋友们后续的分享交流。

**Comment by pierre94** [comment]
期待

**Comment by shenzhuan** [comment]
https://gitee.com/catshen/zscat_sw 这个项目咋样 可以在里面集成各种案例
