### ISSUE TITLE
【补充知识 】缓存与数据库的双写一致性，主动通过mysql binlog 同步redis

### ISSUE THREAD

**Issue by lightfish-zhang** [doocs/advanced-java#47]
参考这个项目
https://github.com/liukelin/canal_mysql_nosql_sync
基于canal 的 mysql 与 redis/memcached/mongodb 的 nosql 数据实时同步方案

**Comment by yanglbme** [comment]
@lightfish-zhang 谢谢分享 :)

此项目偏实战应用，文档写得不是很好，我打个 Label，读者若有需要，直接通过你推荐的链接去看哈~
