### ISSUE TITLE
作者的内容只能稍微用来参考，回答的不仅不全面，而且只侧重表明。 例如：如何保证消息不被重复消费？或者说，如何保证消息消费的幂等性？

### ISSUE THREAD

**Issue by 156235yuan** [doocs/advanced-java#50]
如何保证消息不被重复消费？或者说，如何保证消息消费的幂等性？
消息重复产生可能出现在2个位置，一个是消息发送端的重复发送，一个是消息到达了消息存储，由消息中间件重复投递产生错误。 消息的重复存储也会导致消息重复投递，而被重复消费，可以在消息发送至存储前给消息加入唯一ID，保证存储的唯一性。而针对重复投递的消息，有两种方式，一个是可以采用分布式事物来解决，一个是消息接收者的操作是幂等操作。

**Comment by 156235yuan** [comment]
用来当题库还是可以的，但是回答的内容还是建议直接查资料或者看书吧.....

**Comment by yanglbme** [comment]
@156235yuan 谢谢反馈，这个知识仓库的定位就是“扫盲“，我想 title 都写得很清楚的... 看书可以更加深入某一块的知识，这毋庸置疑。
