### ISSUE TITLE
图片在本地不能正常显示的问题

### ISSUE THREAD

**Issue by SJP-github** [doocs/advanced-java#58]
fork项目后，把项目拉倒本地用idea查看（因为用github比较卡，即使用了Octotree查看还是不太方便），结果图片不能正常显示。在markdown中是存在这样的问题，不知道有没有什么好的解决方案

**Comment by yanglbme** [comment]
@SJP-github 同学你好。

- 本项目文章中的图片全部是采用 `!()[]` 相对引用引入，应该是可以正常显示的。对于整个项目，我都是基于 VSCode 来编辑的。VSCode 下都能正常显示。
![image](https://user-images.githubusercontent.com/21008209/55766250-678ee600-5aa6-11e9-9a4d-8487d6180575.png)

- 因为项目没有涉及到多少实际的编码，个人觉得没有必要打开 IDEA 这个大型软件来阅读文章，VSCode 就很小巧，打开速度也快。

- 后续可以将项目同步到 Gitee，这样国内的访问速度就很快了。

**Comment by SJP-github** [comment]
感谢提醒，我试试

**Comment by yanglbme** [comment]
@SJP-github 你好，上午我花了些时间，将项目同步到码云上了，可以访问 https://doocs.gitee.io/advanced-java 来阅读，访问速度上应该没问题了。

**Comment by SJP-github** [comment]
真的十分感谢！辛苦了，大哥。

在 2019-04-16 13:48:07，"Libin Yang" <notifications@github.com> 写道：


@SJP-github 你好，上午我花了些时间，将项目同步到码云上了，可以访问 https://doocs.gitee.io/advanced-java 来阅读，访问速度上应该没问题了。
