### ISSUE TITLE
gitpage浏览子页面无法滚动，控制台有报错

### ISSUE THREAD

**Issue by ishenyi** [doocs/advanced-java#6]
![image](https://user-images.githubusercontent.com/15214043/50419228-b489dc00-086a-11e9-84de-f6b70a3a17b2.png)

chrome 71.0.3578.98 macos10.13.6

**Comment by yanglbme** [comment]
@ishenyi 谢谢反馈，我的 chrome 也是这个版本，子页面可以滚动。我用的是 windows，不清楚 macos 下是什么个情况，可能需要向 [docsify](https://github.com/docsifyjs/docsify/issues) 维护方反馈一下这个问题。

至于 404，是因为 docsify 会加载每个文件夹下的导航页，这个项目里不需要每个子目录都添加导航页，应该不影响~

**Comment by yanglbme** [comment]
我把其它一些不必要的配置删掉吧~
