### ISSUE TITLE
能新增一个关于JVM跟一些Java知识点相关的版块吗

### ISSUE THREAD

**Issue by siegluo** [doocs/advanced-java#64]
作为Java面试扫盲，能新增一个关于JVM跟一些Java知识点相关的版块吗？感觉面试挺多的

**Comment by yanglbme** [comment]
@siegluo 谢谢反馈。

- 关于 JVM 的一些知识，可以参考 [doocs/jvm](https://github.com/doocs/jvm) 下的知识总结，而更详细的 JVM 相关知识，推荐阅读周志民老师的《深入理解 Java 虚拟机》。
- 关于 Java 相关的知识点，这个涉及到的东西太多了，以后可能会开新的 GitHub 仓库系统性更新这一块的知识点。真的要做的话，是需要投入大量的时间、精力才能完成的，因为我对于 GitHub 项目的质量有很高的要求，而现在每天忙不过来，所以暂时不开哈。当然，如果你现在需要的话，可以先看看 [JavaGuide](https://github.com/SnailClimb/JavaGuide)。
