### ISSUE TITLE
MQ中的kafka高可用描述不完整

### ISSUE THREAD

**Issue by joyway66** [doocs/advanced-java#67]
![MQ](https://user-images.githubusercontent.com/18898878/57745317-49e51a00-76ff-11e9-9ff1-db5630d83fac.png)

如上圈起来的地方，“如果这上面有某个partition的leader”，应该修改为“如果这上面有某个partition的leader挂掉了”

**Comment by yanglbme** [comment]
@joyway66 哈喽，谢谢反馈，原文其实就是这个意思。broker 宕机，没事，副本还在。即便宕机的包括了 leader，也可以重新选举一个新的 leader 出来。

**Comment by yanglbme** [comment]
我重新修改下描述吧
