### ISSUE TITLE
Doocs 微信交流群 | Wechat group for Doocs

### ISSUE THREAD

**Issue by yanglbme** [doocs/advanced-java#70]
1. 微信群禁止一切垃圾广告信息，包括小程序助力信息、小游戏、社群推广、公众号推广、支付宝推广码等；
1. 交流 GitHub、开发相关，可以自由分享开发相关知识，不提倡整天水群；

**更新**：**目前群人数已超 100**，可添加我私人微信（备注：个人姓名+来自 GitHub，微商广告党勿加），私聊我拉入 Doocs 交流群。

[<img src="https://raw.githubusercontent.com/doocs/advanced-java/master/images/qrcode_for_yanglbme.jpg"  width="60%"/>](https://raw.githubusercontent.com/doocs/intro/master/images/qrcode_for_yanglbme.jpg)

**Comment by leilinen** [comment]
群的二维码已经过期了

**Comment by yanglbme** [comment]
@leilinen 群人数也超 100 了。若想进群，可以扫右边二维码加我微信，我拉你进群。
