### ISSUE TITLE
这个是抄石杉码农的吧？

### ISSUE THREAD

**Issue by stillwindows7** [doocs/advanced-java#72]
这个是抄石杉码农的吧？

**Comment by yanglbme** [comment]
请看 [分享一套GitHub上stars 10000+的Java面试题（含解析）【石杉的架构笔记】](https://mp.weixin.qq.com/s/abjdjuoNUobZr5Rv1RqkBA)

**Comment by yanglbme** [comment]
@stillwindows7 我想 README 文档已经写得很清楚了，问问题之前麻烦查看一下文档和已有 Issues。
