### ISSUE TITLE
关于MQ批量重导

### ISSUE THREAD

**Issue by fredwangwang** [doocs/advanced-java#73]
感谢编写这么好的内容！但是关于批量重导由于自己没有做过深入的研究，能不能写一下MQ在数据丢失后的批量重导是怎么工作的？

谢谢！

https://github.com/doocs/advanced-java/blame/master/docs/high-concurrency/mq-time-delay-and-expired-failure.md#L27

**Comment by yanglbme** [comment]
@fredwangwang 就是重新把那批丢失的数据查出来，发送到 MQ 中，让消费端进行消费。

**Comment by fredwangwang** [comment]
@yanglbme 谢谢回答！就是把丢失数据查出来这部分是怎么完成的？ 过了有效期之后数据不就被删除了嘛？

**Comment by yanglbme** [comment]
@fredwangwang 不一定就直接被删了，可以进入死信队列，后续再做处理。你可以查阅消息队列相关资料，详细了解一下。
