### ISSUE TITLE
如何设计可以动态扩容缩容的分库分表方案 一个疑问

### ISSUE THREAD

**Issue by hunao0221** [doocs/advanced-java#79]
> 4. 由 dba 负责将原先数据库服务器的库，迁移到新的数据库服务器上去，库迁移是有一些便捷的工具的。
总结的第四点，在第三点中成倍扩容之后，为什么需要进行库迁移？而不是根据新的路由规则，将新的数据写入新的库呢？

**Comment by yanglbme** [comment]
前面也说明了，就是说刚开始建了这个 n 多个(逻辑)库，可能在同一台 DB 服务器上。之后 DB 服务器新增扩容，就把原先的一些 DB 迁移到新的 DB 服务器上。

**Comment by hunao0221** [comment]
> 前面也说明了，就是说刚开始建了这个 n 多个(逻辑)库，可能在同一台 DB 服务器上。之后 DB 服务器新增扩容，就把原先的一些 DB 迁移到新的 DB 服务器上。

感谢，又仔细看了一遍，算是明白了！

**Comment by 472630126** [comment]
我有一个疑问，为什么说成倍扩容了之后， 路由逻辑不需要改变呢。   比如我原来是32个库  ， 扩容成 64 ，   那不是要把  orderId%32  改成  orderId%64吗 ？   还有这样的话， 依然会有数据会落到 前32个库 。  这样扩容，每扩容一次，前面的库的数据都会增加，  不用做均衡迁移吗。
