### ISSUE TITLE
项目本地查看

### ISSUE THREAD

**Issue by WangYangA9** [doocs/advanced-java#80]
请问项目中这种 /images/xxxxx.png路径的图片，在本地用什么软件能加载出来

**Comment by yanglbme** [comment]
@WangYangA9 我项目文章是在 VSCode 里编辑的，图文均可可正常预览。

**Comment by WangYangA9** [comment]
@yanglbme VSCode很棒棒，Idea和Typora配了半天都不行。Typora已被打入冷宫

**Comment by yanglbme** [comment]
@WangYangA9 VSCode 是真的好用
