### ISSUE TITLE
关于如何保证消息的可靠性传输的一个疑问

### ISSUE THREAD

**Issue by zhangchaowu** [doocs/advanced-java#82]
关闭自动ack的做法，是否可以解决生产端、mq、消费端丢失的消息的问题，如果是的话，关闭ack这种做法会有什么弊端吗？

**Comment by yanglbme** [comment]
@zhangchaowu 关闭自动 ack 的做法而改成手动 ack，仅能确保消费者在消费完消息之后再发送 ack，保证消费端不丢失消息而已。整个链路保证消息不丢失，需要以下多个方面都做好。

![](https://github.com/doocs/advanced-java/raw/master/images/rabbitmq-message-lose-solution.png)

关闭自动 ack 之后，开发人员就需要手动进行 ack，不要遗忘了这一步就好。
