### ISSUE TITLE
关于es分页查询并且排序不准确问题提问

### ISSUE THREAD

**Issue by InvokerPeng** [doocs/advanced-java#86]
我做的项目在进行分页排序查询的时候会出现不准确问题，我这边集群环境是2个节点，每个节点都有5个分片，现在我进行2个字段联合排序后想进行分页取回，每页10条，目前总的数据量有1700条，但是按照分页取出来的是不准的，看数据结果集 应该是每个分片都取了10条，然后按照分片顺序直接合在一起了，是01234这5个分片的的各10条按照分片顺序往后排，没有汇总进行总的排序，目前试过更改过searchType来更改搜索类型，都试过都不起作用，想问下有没有好的解决办法，谢谢啊

**Comment by Volong** [comment]
这个是正常现象。
或者在返回的时候加一个排序字段试试看效果

**Comment by InvokerPeng** [comment]
> 这个是正常现象。
> 或者在返回的时候加一个排序字段试试看效果

能否举个例子

**Comment by Volong** [comment]
@InvokerPeng 不会，没用过ES :sweat_smile:
