### ISSUE TITLE
请问如何保证缓存与数据库的双写一致性中的问题

### ISSUE THREAD

**Issue by Blusez** [doocs/advanced-java#89]
[如何保证缓存与数据库的双写一致性？](https://github.com/doocs/advanced-java/blob/master/docs/high-concurrency/redis-consistence.md)
在“最初级的缓存不一致问题及解决方案”这里

- 为什么会出现缓存删除失败这种场景呢？
- 这块有相关代码借鉴一下吗？

**Comment by yanglbme** [comment]
@Blusez 因为你删除缓存，其实是跟 Redis 的一次通信过程。如果出现了网络超时或者其它异常情况，就可能出现缓存删除失败的情况。
