### ISSUE TITLE
关于《亿级流量高并发场景下，如何保证缓存与数据库的双写一致性？》中的疑问

### ISSUE THREAD

**Issue by cy503328434** [doocs/advanced-java#90]
大家有看过 【石杉的架构笔记】公众号推送的文章吗？[亿级流量高并发场景下，如何保证缓存与数据库的双写一致性？](https://mp.weixin.qq.com/s/DOTzj5FkGmP4BeQwyvtzyA) 。里面说到比较复杂的数据不一致问题的解决方案。将操作路由之后，发送到一个 jvm 内部队列中。他需要建很多的内存队列，然后hash到不同的队列去排队，一个队列对应一个工作线程，每个工作线程串行拿到对应的操作，然后一条一条的执行。我觉得这样子处理是不是有些过于复杂了， 是不是可以通过java里面的读写锁来实现就可以了，写的时候对这个key加写锁，直接写成功才返回，在写的时候不能对这个key进行读操作。如果长时候拿不到读锁我们也可以类似他说的那样来优化。

**Comment by TheMrCoder** [comment]
@cy503328434 一样的，读写锁是基于AbstractQueuedSynchronizer实现的，多个请求到来时，也是在队列里管理请求线程，排队执行。直接使用队列的话，可以过滤掉相同的更新缓存的请求。

**Comment by cy503328434** [comment]
> @cy503328434 一样的，读写锁是基于AbstractQueuedSynchronizer实现的，多个请求到来时，也是在队列里管理请求线程，排队执行。直接使用队列的话，可以过滤掉相同的更新缓存的请求。

但是java里面能支持对于不用的key生成不同的读写锁吗，这个应该是要把不用的key去拿不同的锁，不然会出现问题

**Comment by TheMrCoder** [comment]
@cy503328434 嗯，是需要多个锁的，目的和使用多个队列提高处理效率一样。可以使用hash等方式让相同的key请求相同的锁。所以总的来说，不论是用锁还是队列，目的都是让写和读在适当的时候串行执行，这个适当的时候就是：缓存中对应的值不存在（被删除了）。

**Comment by cy503328434** [comment]
> @cy503328434 嗯，是需要多个锁的，目的和使用多个队列提高处理效率一样。可以使用hash等方式让相同的key请求相同的锁。所以总的来说，不论是用锁还是队列，目的都是让写和读在适当的时候串行执行，这个适当的时候就是：缓存中对应的值不存在（被删除了）。

对，只要串行化处理就好了。

**Comment by zoujs** [comment]
这种方案的前提应该是特定的id会被路由到特定的机器上吧，如果机器扩容了呢？
