### ISSUE TITLE
关于《如何解决消息队列的延时以及过期失效问题？消息队列满了以后该怎么处理？有几百万消息持续积压几小时，说说怎么解决？》的疑问

### ISSUE THREAD

**Issue by gwcai** [doocs/advanced-java#91]
"大量消息在 mq 里积压了几个小时了还没解决"解决方案最后一条：
<得恢复原先部署的架构，重新用原先的 consumer 机器来消费消息>

疑问：producer继续往原topic写数据，consumer继续往原topic消费数据，那新建扩充的topic里面的数据怎么办？也用原consumer来消费吗，那consumer还是需要很长时间来消费？

**Comment by yanglbme** [comment]
@gwcai 前面几步是为了快速消费积压的数据，等消费得差不多，高峰期也过了的时候，就恢复原先的架构就好了。
