### ISSUE TITLE
瞎JI BA 装逼

### ISSUE THREAD

**Issue by iteeks** [doocs/advanced-java#99]

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/63675333-2a3fb080-c81b-11e9-8309-09da7b8f21d3.png)
![image](https://user-images.githubusercontent.com/21008209/63675359-37f53600-c81b-11e9-9285-9ff633b5fe8b.png)


**下午两点 37 注册了个小号，两点 39 就来开 Issue 喷我？谁派你来的？**

**Comment by NoOneHero** [comment]
??




------------------ 原始邮件 ------------------
发件人: "iteeks"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 下午2:41
收件人: "doocs/advanced-java"<advanced-java@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [doocs/advanced-java] 瞎JI BA 装逼 (#99)

**Comment by chenqimiao** [comment]
@yanglbme 举报一波
